### PR TITLE
upgrade graceful-fs to 4.1.3

### PR DESCRIPTION
**Pull request by thefourtheye**
ref: https://github.com/krakenjs/engine-munger/issues/46

### CODE REVIEW

**Comment by skoranga** [comment]
:+1: 
@thefourtheye can you submit another PR for `0.2.x` branch as well - https://github.com/krakenjs/engine-munger/tree/v0.2.x?

**Comment by thefourtheye** [comment]
@skoranga Done! PTAL.

**Comment by grawk** [comment]
:+1:

**Comment by ChALkeR** [comment]
Note that this fix is not complete, `file-resolver@1.0.2` depends on `graceful-fs@2.0.3`.

**Pull request merged**
