### PR TITLE
Fix dequeue of pending stats

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by grawk** [comment]
:+1:

**Comment by brakon** [comment]
Approved? :P

**Comment by aredridel** [comment]
Published as 1.1.1

**Comment by brakon** [comment]
Makara is the one using engine-munger, and Makara's package.json has the dependency set to be "engine-munger": "v1.0.0" so the fix wont show up.

Any plans to update this?

**Comment by aredridel** [comment]
Doh. That should a been ^ .. Will fix tonight

**Comment by aredridel** [comment]
`makara@2.0.2`

**Pull request merged**
